/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWazapRouteImport } from './routes/api/wazap'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as appTodoRouteImport } from './routes/(app)/todo'
import { Route as appShoppingRouteImport } from './routes/(app)/shopping'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appAppWeekRouteImport } from './routes/(app)/app/week'
import { Route as appAppDayRouteImport } from './routes/(app)/app/day'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWazapRoute = ApiWazapRouteImport.update({
  id: '/api/wazap',
  path: '/api/wazap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appTodoRoute = appTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => appRouteRoute,
} as any)
const appShoppingRoute = appShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppWeekRoute = appAppWeekRouteImport.update({
  id: '/app/week',
  path: '/app/week',
  getParentRoute: () => appRouteRoute,
} as any)
const appAppDayRoute = appAppDayRouteImport.update({
  id: '/app/day',
  path: '/app/day',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/shopping': typeof appShoppingRoute
  '/todo': typeof appTodoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/wazap': typeof ApiWazapRoute
  '/app/day': typeof appAppDayRoute
  '/app/week': typeof appAppWeekRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/shopping': typeof appShoppingRoute
  '/todo': typeof appTodoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/wazap': typeof ApiWazapRoute
  '/app/day': typeof appAppDayRoute
  '/app/week': typeof appAppWeekRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/(app)/shopping': typeof appShoppingRoute
  '/(app)/todo': typeof appTodoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/wazap': typeof ApiWazapRoute
  '/(app)/app/day': typeof appAppDayRoute
  '/(app)/app/week': typeof appAppWeekRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/shopping'
    | '/todo'
    | '/api/chat'
    | '/api/wazap'
    | '/app/day'
    | '/app/week'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/shopping'
    | '/todo'
    | '/api/chat'
    | '/api/wazap'
    | '/app/day'
    | '/app/week'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/about'
    | '/login'
    | '/signup'
    | '/(app)/shopping'
    | '/(app)/todo'
    | '/api/chat'
    | '/api/wazap'
    | '/(app)/app/day'
    | '/(app)/app/week'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiWazapRoute: typeof ApiWazapRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wazap': {
      id: '/api/wazap'
      path: '/api/wazap'
      fullPath: '/api/wazap'
      preLoaderRoute: typeof ApiWazapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/todo': {
      id: '/(app)/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof appTodoRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/shopping': {
      id: '/(app)/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof appShoppingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app/week': {
      id: '/(app)/app/week'
      path: '/app/week'
      fullPath: '/app/week'
      preLoaderRoute: typeof appAppWeekRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/app/day': {
      id: '/(app)/app/day'
      path: '/app/day'
      fullPath: '/app/day'
      preLoaderRoute: typeof appAppDayRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appShoppingRoute: typeof appShoppingRoute
  appTodoRoute: typeof appTodoRoute
  appAppDayRoute: typeof appAppDayRoute
  appAppWeekRoute: typeof appAppWeekRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appShoppingRoute: appShoppingRoute,
  appTodoRoute: appTodoRoute,
  appAppDayRoute: appAppDayRoute,
  appAppWeekRoute: appAppWeekRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiWazapRoute: ApiWazapRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
