/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWazapRouteImport } from './routes/api/wazap'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiEmilaRouteImport } from './routes/api/emila'
import { Route as ApiDeletionRouteImport } from './routes/api/deletion'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as appTodoRouteImport } from './routes/(app)/todo'
import { Route as appShoppingRouteImport } from './routes/(app)/shopping'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appCalWeekRouteImport } from './routes/(app)/cal/week'
import { Route as appCalScheduleRouteImport } from './routes/(app)/cal/schedule'
import { Route as appCalDayRouteImport } from './routes/(app)/cal/day'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWazapRoute = ApiWazapRouteImport.update({
  id: '/api/wazap',
  path: '/api/wazap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmilaRoute = ApiEmilaRouteImport.update({
  id: '/api/emila',
  path: '/api/emila',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeletionRoute = ApiDeletionRouteImport.update({
  id: '/api/deletion',
  path: '/api/deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appTodoRoute = appTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => appRouteRoute,
} as any)
const appShoppingRoute = appShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appCalWeekRoute = appCalWeekRouteImport.update({
  id: '/cal/week',
  path: '/cal/week',
  getParentRoute: () => appRouteRoute,
} as any)
const appCalScheduleRoute = appCalScheduleRouteImport.update({
  id: '/cal/schedule',
  path: '/cal/schedule',
  getParentRoute: () => appRouteRoute,
} as any)
const appCalDayRoute = appCalDayRouteImport.update({
  id: '/cal/day',
  path: '/cal/day',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/profile': typeof appProfileRoute
  '/shopping': typeof appShoppingRoute
  '/todo': typeof appTodoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deletion': typeof ApiDeletionRoute
  '/api/emila': typeof ApiEmilaRoute
  '/api/test': typeof ApiTestRoute
  '/api/wazap': typeof ApiWazapRoute
  '/cal/day': typeof appCalDayRoute
  '/cal/schedule': typeof appCalScheduleRoute
  '/cal/week': typeof appCalWeekRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/profile': typeof appProfileRoute
  '/shopping': typeof appShoppingRoute
  '/todo': typeof appTodoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deletion': typeof ApiDeletionRoute
  '/api/emila': typeof ApiEmilaRoute
  '/api/test': typeof ApiTestRoute
  '/api/wazap': typeof ApiWazapRoute
  '/cal/day': typeof appCalDayRoute
  '/cal/schedule': typeof appCalScheduleRoute
  '/cal/week': typeof appCalWeekRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/shopping': typeof appShoppingRoute
  '/(app)/todo': typeof appTodoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/deletion': typeof ApiDeletionRoute
  '/api/emila': typeof ApiEmilaRoute
  '/api/test': typeof ApiTestRoute
  '/api/wazap': typeof ApiWazapRoute
  '/(app)/cal/day': typeof appCalDayRoute
  '/(app)/cal/schedule': typeof appCalScheduleRoute
  '/(app)/cal/week': typeof appCalWeekRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/profile'
    | '/shopping'
    | '/todo'
    | '/api/chat'
    | '/api/deletion'
    | '/api/emila'
    | '/api/test'
    | '/api/wazap'
    | '/cal/day'
    | '/cal/schedule'
    | '/cal/week'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/profile'
    | '/shopping'
    | '/todo'
    | '/api/chat'
    | '/api/deletion'
    | '/api/emila'
    | '/api/test'
    | '/api/wazap'
    | '/cal/day'
    | '/cal/schedule'
    | '/cal/week'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/about'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/(app)/profile'
    | '/(app)/shopping'
    | '/(app)/todo'
    | '/api/chat'
    | '/api/deletion'
    | '/api/emila'
    | '/api/test'
    | '/api/wazap'
    | '/(app)/cal/day'
    | '/(app)/cal/schedule'
    | '/(app)/cal/week'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDeletionRoute: typeof ApiDeletionRoute
  ApiEmilaRoute: typeof ApiEmilaRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiWazapRoute: typeof ApiWazapRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wazap': {
      id: '/api/wazap'
      path: '/api/wazap'
      fullPath: '/api/wazap'
      preLoaderRoute: typeof ApiWazapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emila': {
      id: '/api/emila'
      path: '/api/emila'
      fullPath: '/api/emila'
      preLoaderRoute: typeof ApiEmilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deletion': {
      id: '/api/deletion'
      path: '/api/deletion'
      fullPath: '/api/deletion'
      preLoaderRoute: typeof ApiDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/todo': {
      id: '/(app)/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof appTodoRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/shopping': {
      id: '/(app)/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof appShoppingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/cal/week': {
      id: '/(app)/cal/week'
      path: '/cal/week'
      fullPath: '/cal/week'
      preLoaderRoute: typeof appCalWeekRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cal/schedule': {
      id: '/(app)/cal/schedule'
      path: '/cal/schedule'
      fullPath: '/cal/schedule'
      preLoaderRoute: typeof appCalScheduleRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cal/day': {
      id: '/(app)/cal/day'
      path: '/cal/day'
      fullPath: '/cal/day'
      preLoaderRoute: typeof appCalDayRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appProfileRoute: typeof appProfileRoute
  appShoppingRoute: typeof appShoppingRoute
  appTodoRoute: typeof appTodoRoute
  appCalDayRoute: typeof appCalDayRoute
  appCalScheduleRoute: typeof appCalScheduleRoute
  appCalWeekRoute: typeof appCalWeekRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appProfileRoute: appProfileRoute,
  appShoppingRoute: appShoppingRoute,
  appTodoRoute: appTodoRoute,
  appCalDayRoute: appCalDayRoute,
  appCalScheduleRoute: appCalScheduleRoute,
  appCalWeekRoute: appCalWeekRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDeletionRoute: ApiDeletionRoute,
  ApiEmilaRoute: ApiEmilaRoute,
  ApiTestRoute: ApiTestRoute,
  ApiWazapRoute: ApiWazapRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
